spring.application.name=my-finances

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.docker.compose.lifecycle-management=start_only

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.temperature=0.0

spring.ai.elevenlabs.api-key=${ELEVENLABS_API_KEY}
spring.ai.model.audio.speech=elevenlabs
spring.ai.elevenlabs.tts.model-id=eleven_v3
spring.ai.elevenlabs.tts.voice-id=JBFqnCBsd6RMkjVDRZzb
spring.ai.elevenlabs.tts.output-format=mp3_22050_32