spring.application.name=my-finances

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.docker.compose.lifecycle-management=start_only

spring.ai.google.genai.api-key={GOOGLE_API_KEY}